server:
  port: 4000
spring:
  application:
    name: yijiang-mall-auth
  redis:
    host: 192.168.17.128
    password: 7AjyVFT6bGfeobvk
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
